[Desktop Entry]
Type=Service
Exec=blubb
Comment=Lets you manage your git repository.
Comment[ca]=Permet gestionar el vostre repositori git.
Comment[nl]=Laat u uw git-repository beheren.
Comment[pt]=Permite-lhe gerir o seu repositório do Git.
Comment[sv]=Låter dig hantera Git-arkiv.
Comment[uk]=Надає вам змогу керувати вашим сховищем git.
Comment[x-test]=xxLets you manage your git repository.xx
Name=Save System View
Name[ca]=Desa la vista del sistema
Name[nl]=Systeemweergave opslaan
Name[pt]=Gravar a Área do Sistema
Name[sv]=Spara systemvy
Name[uk]=Збереження вигляду системи
Name[x-test]=xxSave System Viewxx
GenericName=Save System View
GenericName[ca]=Desa la vista del sistema
GenericName[nl]=Systeemweergave opslaan
GenericName[pt]=Gravar a Área do Sistema
GenericName[sv]=Spara systemvy
GenericName[uk]=Зберегти вигляд системи
GenericName[x-test]=xxSave System Viewxx
Icon=plasmagik
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevsavesystemview
X-KDE-PluginInfo-Name=KDevSaveSystemView
X-KDE-PluginInfo-Author=Giorgos Tsiapaliokas
X-KDE-PluginInfo-License=LGPL
X-KDE-PluginInfo-Category=Core
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Global
X-KDevelop-Mode=GUI

