[Desktop Entry]
Type=Service
Exec=blubb
Comment=Lets you manage your git repository.
Comment[ast]=Déxate xestionar el to repositoriu git.
Comment[ca]=Permet gestionar el vostre repositori git.
Comment[de]=Verwaltung von Git-Quelltextarchiven.
Comment[en_GB]=Lets you manage your git repository.
Comment[es]=Le permite gestionar su repositorio git.
Comment[fi]=Mahdollistaa git-varaston hallinnan.
Comment[gl]=Permítelle xestionar o seu repositorio Git.
Comment[hu]=Lehetővé teszi git tárolóinak kezelését.
Comment[it]=Consente di gestire il vostro deposito git.
Comment[nl]=Laat u uw git-repository beheren.
Comment[pl]=Umożliwia zarządzanie twoimi repozytoriami git.
Comment[pt]=Permite-lhe gerir o seu repositório do Git.
Comment[pt_BR]=Permite-lhe gerenciar seu repositório Git.
Comment[sk]=Nechá vás spravovať váš git repozitár.
Comment[sl]=Omogoči upravljanje s skladiščem git.
Comment[sv]=Låter dig hantera Git-arkiv.
Comment[tr]=Git deponuzu yönetmenize izin verir.
Comment[uk]=Надає вам змогу керувати вашим сховищем git.
Comment[x-test]=xxLets you manage your git repository.xx
Name=Save System View
Name[ca]=Desa la vista del sistema
Name[de]=Systemansicht speichern
Name[en_GB]=Save System View
Name[es]=Guardar vista del sistema
Name[fi]=Tallenna järjestelmän näkymä
Name[gl]=Gardar a vista do sistema
Name[hu]=Rendszernézet mentése
Name[it]=Vista sistema di salvataggio
Name[nl]=Systeemweergave opslaan
Name[pl]=Zapisz widok systemu
Name[pt]=Gravar a Área do Sistema
Name[pt_BR]=Salvar a Área do Sistema
Name[sk]=Uložiť systémový pohľad
Name[sl]=Pogled sistema za shranjevanje
Name[sv]=Spara systemvy
Name[tr]=Sistem Görünümünü Kaydet
Name[uk]=Збереження вигляду системи
Name[x-test]=xxSave System Viewxx
GenericName=Save System View
GenericName[ca]=Desa la vista del sistema
GenericName[de]=Systemansicht speichern
GenericName[en_GB]=Save System View
GenericName[es]=Guardar vista del sistema
GenericName[fi]=Tallenna järjestelmän näkymä
GenericName[gl]=Gardar a vista do sistema
GenericName[hu]=Rendszernézet mentése
GenericName[it]=Vista sistema di salvataggio
GenericName[nl]=Systeemweergave opslaan
GenericName[pl]=Zapisz widok systemu
GenericName[pt]=Gravar a Área do Sistema
GenericName[pt_BR]=Salvar a Área do Sistema
GenericName[sk]=Uložiť systémový pohľad
GenericName[sl]=Pogled sistema za shranjevanje
GenericName[sv]=Spara systemvy
GenericName[tr]=Sistem Görünümünü Kaydet
GenericName[uk]=Зберегти вигляд системи
GenericName[x-test]=xxSave System Viewxx
Icon=plasmagik
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevsavesystemview
X-KDE-PluginInfo-Name=KDevSaveSystemView
X-KDE-PluginInfo-Author=Giorgos Tsiapaliokas
X-KDE-PluginInfo-License=LGPL
X-KDE-PluginInfo-Category=Core
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Global
X-KDevelop-Mode=GUI

