# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kauth': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/kpackage': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/ksvg': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/solid': '@latest-kf6'
    'frameworks/sonnet': '@latest-kf6'
    'frameworks/syntax-highlighting': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'plasma/libplasma': '@same'
    'plasma/plasma5support': '@same'
Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
 run-qmllint: true
