[Desktop Entry]
Type=Service
Name=Plasma Project Manager
Name[pt]=Gestor de Projectos do Plasma
Name[sv]=Plasma-projekthanterare
Name[uk]=Керування проектами Плазми
Name[x-test]=xxPlasma Project Managerxx
GenericName=Plasma Project Manager
GenericName[pt]=Gestor de Projectos do Plasma
GenericName[sv]=Plasma-projekthanterare
GenericName[uk]=Керування проектами Плазми
GenericName[x-test]=xxPlasma Project Managerxx
Comment=Allow KDevPlatform to manage plasma projects
Comment[pt]=Permite ao KDevPlatform gerir projectos do Plasma
Comment[sv]=Tillåter att KDevelop hanterar Plasma-projekt
Comment[uk]=Дозволяє KDevPlatform керувати проектами Плазми
Comment[x-test]=xxAllow KDevPlatform to manage plasma projectsxx
Icon=plasmagik
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevplatform/@KDEV_PLUGIN_VERSION@/kdevplasmamanager
X-KDE-PluginInfo-Name=KDevPlasmaManager
X-KDevelop-FileManager=None
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Project
X-KDevelop-Interfaces=org.kdevelop.IProjectFileManager
X-KDE-PluginInfo-Author=Giorgos Tsiapaliokas
X-KDE-PluginInfo-Category=Project Management
X-KDevelop-Mode=GUI

