[Desktop Entry]
Type=Service
Name=Plasma Project Manager
Name[ast]=Xestor de proyeutos de plasma
Name[ca]=Gestor de projectes Plasma
Name[ca@valencia]=Gestor de projectes Plasma
Name[de]=Plasma-Projektverwaltung
Name[en_GB]=Plasma Project Manager
Name[es]=Gestor de proyectos de Plasma
Name[et]=Plasma projektihaldur
Name[fi]=Plasma-projektinhallinta
Name[gl]=Xestor de proxectos de Plasma
Name[it]=Gestore progetto Plasma
Name[ko]=Plasma 프로젝트 관리자
Name[nl]=Plasma projectbeheerder
Name[nn]=Plasma prosjekthandsamar
Name[pl]=Zarządzanie projektami Plazmy
Name[pt]=Gestor de Projectos do Plasma
Name[pt_BR]=Gerenciador de Projetos do Plasma
Name[ru]=Диспетчер проектов Plasma
Name[sk]=Správca projektov Plasma
Name[sl]=Upravljalnik projektov za Plasmo
Name[sr]=Менаџер плазма пројеката
Name[sr@ijekavian]=Менаџер плазма пројеката
Name[sr@ijekavianlatin]=Menadžer plasma projekata
Name[sr@latin]=Menadžer plasma projekata
Name[sv]=Plasma-projekthanterare
Name[uk]=Керування проектами Плазми
Name[x-test]=xxPlasma Project Managerxx
Name[zh_CN]=Plasma 工程管理器
GenericName=Plasma Project Manager
GenericName[ast]=Xestor de proyeutos de plasma
GenericName[ca]=Gestor de projectes del Plasma
GenericName[ca@valencia]=Gestor de projectes Plasma
GenericName[de]=Plasma-Projektverwaltung
GenericName[en_GB]=Plasma Project Manager
GenericName[es]=Gestor de proyectos de Plasma
GenericName[et]=Plasma projektihaldur
GenericName[fi]=Plasma-projektinhallinta
GenericName[gl]=Xestor de proxectos de Plasma
GenericName[it]=Gestore progetto Plasma
GenericName[ko]=Plasma 프로젝트 관리자
GenericName[nl]=Plasma projectbeheerder
GenericName[nn]=Plasma prosjekthandsamar
GenericName[pl]=Zarządzanie projektami Plazmy
GenericName[pt]=Gestor de Projectos do Plasma
GenericName[pt_BR]=Gerenciador de Projetos do Plasma
GenericName[ru]=Диспетчер проектов Plasma
GenericName[sk]=Správca projektov Plasma
GenericName[sl]=Upravljalnik projektov za Plasmo
GenericName[sr]=Менаџер плазма пројеката
GenericName[sr@ijekavian]=Менаџер плазма пројеката
GenericName[sr@ijekavianlatin]=Menadžer plasma projekata
GenericName[sr@latin]=Menadžer plasma projekata
GenericName[sv]=Plasma-projekthanterare
GenericName[uk]=Керування проектами Плазми
GenericName[x-test]=xxPlasma Project Managerxx
GenericName[zh_CN]=Plasma 工程管理器
Comment=Allow KDevPlatform to manage plasma projects
Comment[ast]=Permite a KDevPlatform xestionar los proyeutos de plasma
Comment[ca]=Permet al KDevPlatform gestionar els projectes del Plasma
Comment[ca@valencia]=Permet al KDevPlatform gestionar els projectes de plasma
Comment[de]=Verwaltung von Plasma-Projekten mit KDevPlatform
Comment[en_GB]=Allow KDevPlatform to manage plasma projects
Comment[es]=Permite a KDevPlatform gestionar proyectos de Plasma
Comment[et]=Võimaldab KDevPlatformil hallata Plasma projekte
Comment[fi]=Mahdollistaa KDevPlatformin hallitsemaan Plasma-projekteja
Comment[gl]=Permitir que KDevPlatform xestione proxectos de Plasma.
Comment[it]=Permette a KDevPlatform di gestire i progetti di plasma
Comment[ko]=KDevPlatform으로 Plasma 프로젝트 관리 허용
Comment[nl]=KDevPlatform toestaan plasma-projecten te beheren
Comment[nn]=Tillet KDevPlatform å handtera Plasma-prosjekt
Comment[pl]=Zezwól KDevPlatform na zarządzanie projektami plazmy
Comment[pt]=Permite ao KDevPlatform gerir projectos do Plasma
Comment[pt_BR]=Permite ao KDevPlatform gerenciar projetos do Plasma
Comment[sk]=Umožniť KDevPlatform spracovať projekty plasma
Comment[sl]=Omogoči, da KDevPlatform upravlja s projekti Plasme
Comment[sr]=Дозволите К‑девелопу да управља плазма пројектима
Comment[sr@ijekavian]=Дозволите К‑девелопу да управља плазма пројектима
Comment[sr@ijekavianlatin]=Dozvolite KDevelopu da upravlja plasma projektima
Comment[sr@latin]=Dozvolite KDevelopu da upravlja plasma projektima
Comment[sv]=Tillåter att KDevelop hanterar Plasma-projekt
Comment[uk]=Дозволяє KDevPlatform керувати проектами Плазми
Comment[x-test]=xxAllow KDevPlatform to manage plasma projectsxx
Comment[zh_CN]=允许 KDevPlatform 管理 plasma 项目
Icon=plasmagik
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevplatform/@KDEV_PLUGIN_VERSION@/kdevplasmamanager
X-KDE-PluginInfo-Name=KDevPlasmaManager
X-KDevelop-FileManager=None
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Category=Project
X-KDevelop-Interfaces=org.kdevelop.IProjectFileManager
X-KDE-PluginInfo-Author=Giorgos Tsiapaliokas
X-KDE-PluginInfo-Category=Project Management
X-KDevelop-Mode=GUI

